import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from "@/components/header";
import BackgroundSlider from "@/components/background-slider";
import About from "@/components/about";
import Video from "@/components/video";
import Prices from "@/components/prices";
import Partners from "@/components/partners";
import Footer from "@/components/footer";
import AgroVideo from "@/components/agro-video";
import Menu from "@/components/menu";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <BackgroundSlider/>
      <About/>
      <Video/>
      <Prices/>
      <AgroVideo/>
      <Partners/>
      <Footer/>
    </>
  )
}
